services:
  odysseygo:
    image: ${DOCKERHUB_USERNAME:-yourusername}/odysseygo:${IMAGE_TAG:-develop}
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    user: root
    restart: unless-stopped
    environment:
      - NETWORK=${NETWORK:-mainnet}
      - BOOTSTRAP_URL=${BOOTSTRAP_URL:-https://odysseygo-bootstraps.nyc3.cdn.digitaloceanspaces.com/odyssey-bootstrap-mainnet.zip}
      - RPC_ACCESS=${RPC_ACCESS:-public}
      - STATE_SYNC=${STATE_SYNC:-off}
      - IP_MODE=${IP_MODE:-dynamic}
      - PUBLIC_IP=${PUBLIC_IP:-0.0.0.0}
      - DB_DIR=${DB_DIR:-/odysseygo/db}
      - LOG_LEVEL_NODE=${LOG_LEVEL_NODE:-info}
      - LOG_LEVEL_DCHAIN=${LOG_LEVEL_DCHAIN:-info}
      - INDEX_ENABLED=${INDEX_ENABLED:-true}
      - ARCHIVAL_MODE=${ARCHIVAL_MODE:-true}
      - ADMIN_API=${ADMIN_API:-false}
      - ETH_DEBUG_RPC=${ETH_DEBUG_RPC:-true}
    volumes:
      - "${PWD}/data/.odysseygo:/odysseygo/.odysseygo"
      - "${PWD}/data/db:/odysseygo/db"
      - "${PWD}/logs:/var/log/odysseygo"
      - "${PWD}/bootstrappers.json:/odysseygo/docker/bootstrappers.json:ro"
    ports:
      - "${RPC_HOST_PORT:-9650}:9650"
      - "${P2P_HOST_PORT:-9651}:9651"
    healthcheck:
      test: >
        curl -sf -H "Content-Type: application/json" -X POST \
          --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", true],"id":1}' \
          http://localhost:9650/ext/bc/D/rpc || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

    networks:
      - odyssey6

networks:
  odyssey6:
    driver: bridge
    enable_ipv6: true