name: Build and Push Docker Image

on:
  push:
    branches:
      - develop  # Trigger on push to main branch

  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/odysseygo:develop \
            ./docker

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/odysseygo:develop

      - name: Image details confirmation
        run: |
          echo "Docker Image ${{ secrets.DOCKERHUB_USERNAME }}/odysseygo:develop pushed successfully!"
